import {
  BadgeCheck,
  Binary,
  Braces,
  Building2,
  Clock3,
  FileText,
  Hash,
  KeyRound,
  Link,
  ShieldCheck,
} from 'lucide-react';
import type { ToolMeta } from '@/shared/types';

export const toolRegistry: ToolMeta[] = [
  {
    id: 'cpf-generator',
    name: 'Gerador de CPF',
    description: 'Gera CPFs válidos para desenvolvimento e testes.',
    category: 'documents',
    path: '/cpf-generator',
    icon: FileText,
  },
  {
    id: 'cpf-validator',
    name: 'Validador de CPF',
    description: 'Valida formato e dígitos verificadores de CPF.',
    category: 'documents',
    path: '/cpf-validator',
    icon: ShieldCheck,
  },
  {
    id: 'cnpj-generator',
    name: 'Gerador de CNPJ',
    description: 'Gera CNPJs válidos para desenvolvimento e testes.',
    category: 'documents',
    path: '/cnpj-generator',
    icon: Building2,
  },
  {
    id: 'cnpj-validator',
    name: 'Validador de CNPJ',
    description: 'Valida formato e dígitos verificadores de CNPJ.',
    category: 'documents',
    path: '/cnpj-validator',
    icon: ShieldCheck,
  },
  {
    id: 'cpf-cnpj-validator',
    name: 'Validador de CPF/CNPJ',
    description: 'Detecta o tipo e valida formato e dígitos verificadores.',
    category: 'documents',
    path: '/cpf-cnpj-validator',
    icon: BadgeCheck,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Formata, valida e minifica JSON.',
    category: 'data',
    path: '/json-formatter',
    icon: Braces,
  },
  {
    id: 'base64-codec',
    name: 'Base64 Codec',
    description: 'Codifica e decodifica texto em Base64.',
    category: 'data',
    path: '/base64',
    icon: Binary,
  },
  {
    id: 'url-codec',
    name: 'URL Codec',
    description: 'Codifica e decodifica componentes de URL.',
    category: 'data',
    path: '/url-codec',
    icon: Link,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decodifica e inspeciona header, payload e metadados de JWT.',
    category: 'data',
    path: '/jwt-decoder',
    icon: KeyRound,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Gera UUIDs para desenvolvimento e testes.',
    category: 'utilities',
    path: '/uuid-generator',
    icon: Hash,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Converte timestamps Unix e datas legíveis.',
    category: 'utilities',
    path: '/timestamp',
    icon: Clock3,
  },
];
