import {
  BadgeCheck,
  Binary,
  Braces,
  Building2,
  Clock3,
  FileText,
  Hash,
  KeyRound,
  Link,
  ShieldCheck,
} from 'lucide-react';
import type { ToolMeta } from '@/shared/types';

export const toolRegistry: ToolMeta[] = [
  {
    id: 'cpf-generator',
    name: 'Gerador de CPF',
    description: 'Gera números de CPF válidos para uso em testes e desenvolvimento.',
    category: 'documents',
    path: '/cpf-generator',
    icon: FileText,
  },
  {
    id: 'cpf-validator',
    name: 'Validador de CPF',
    description: 'Valida números de CPF informados pelo usuário.',
    category: 'documents',
    path: '/cpf-validator',
    icon: ShieldCheck,
  },
  {
    id: 'cnpj-generator',
    name: 'Gerador de CNPJ',
    description: 'Gera números de CNPJ válidos para ambientes de teste.',
    category: 'documents',
    path: '/cnpj-generator',
    icon: Building2,
  },
  {
    id: 'cnpj-validator',
    name: 'Validador de CNPJ',
    description: 'Valida números de CNPJ de forma simples e direta.',
    category: 'documents',
    path: '/cnpj-validator',
    icon: ShieldCheck,
  },
  {
    id: 'cpf-cnpj-validator',
    name: 'Validador CPF/CNPJ',
    description: 'Valida documentos CPF e CNPJ em uma única ferramenta.',
    category: 'documents',
    path: '/cpf-cnpj-validator',
    icon: BadgeCheck,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Formata, valida e minifica JSON de forma estruturada.',
    category: 'data',
    path: '/json-formatter',
    icon: Braces,
  },
  {
    id: 'base64-codec',
    name: 'Base64 Encode/Decode',
    description: 'Codifica e decodifica textos em Base64 com suporte a UTF-8.',
    category: 'data',
    path: '/base64',
    icon: Binary,
  },
  {
    id: 'url-codec',
    name: 'URL Encode/Decode',
    description: 'Codifica e decodifica valores para URL.',
    category: 'data',
    path: '/url-codec',
    icon: Link,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decodifica tokens JWT para inspeção rápida do conteúdo.',
    category: 'data',
    path: '/jwt-decoder',
    icon: KeyRound,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Gera identificadores UUID para uso em desenvolvimento.',
    category: 'utilities',
    path: '/uuid-generator',
    icon: Hash,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Converte timestamps entre formatos comuns.',
    category: 'utilities',
    path: '/timestamp',
    icon: Clock3,
  },
];
